resources:
- name: pipeline-resources
  type: git
  source:
    uri: https://github.com/daggerok/concourse-examples.git
  check_every: 15s
jobs:
- name: pipeline
  public: true
  plan:
  - get: pipeline-resources
    trigger: true
  - task: hola
    file: pipeline-resources/08-destroy-pipeline/resource.yml
