resources:
- name: pipeline-resources
  type: git
  source:
    uri: https://github.com/daggerok/concourse-examples.git
jobs:
- name: pipeline
  public: true
  plan:
  - get: pipeline-resources
  - task: hola
    file: pipeline-resources/05-view-job-output/decomposed-resource.yml
